apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - host: ws.playground.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notification
                port:
                  number: 8080
