apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: grpc
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: websocket
